// image-lint-web/web/components/dropzone.vue
<script>
export default {
	'props': {
		'modelValue': Array
	},
	'methods': {
		'files': function* (dt) {
			let files = [];

			if (dt.items) {
				for (let i of dt.items) {
					yield i.getAsFile();
				}
			} else {
				yield* dt.files;
			}
		},
		'drop': function (e) {
			e.preventDefault();
			this.$refs.dropzone.classList.remove('active');

			const files = Array.from(this.files(e.dataTransfer));

			this.$emit('update:modelValue', files);
		},
		'dragenter': function () {
			this.$refs.dropzone.classList.add('active');
		},
		'dragleave': function () {
			this.$refs.dropzone.classList.remove('active');
		},
		'dragover': function (e) {
			e.preventDefault();
		}
	}
};	
</script>

<template>
	<div class="drop-target" ref="dropzone" @drop="drop" @dragover="dragover" @dragenter="dragenter" @dragleave="dragleave">
		<slot>Drop files here</slot>
	</div>
</template>

<style>
@import "../css/variables.css";

.drop-target {
  height: 100%;
	display: flex;
  justify-content: center;
}

.drop-target.empty {
	align-items: center;
}

.drop-target.active {
  border: 2px dashed var(--color-status-good);
}
</style>

// image-lint-web/src/components/DropZone.tsx
import { useRef, useState, type DragEvent, type PropsWithChildren } from "react";

interface DropZoneProps {
	onDrop: (files: File[]) => void,
	onDragIn?: () => void,
	onDragOut?: () => void
}

export function DropZone ({children, onDrop, onDragIn, onDragOut}: PropsWithChildren<DropZoneProps>) {
	const dropRef = useRef<HTMLDivElement>(null);
	const [active, setActive] = useState(false);

	function* getFiles(dt: DataTransfer): Generator<File, void, undefined> {
		if (dt.items) {
			for (const i of dt.items) {
				const file = i.getAsFile();

				if (file) {
					yield file;
				}
			}
		} else {
			yield* dt.files;
		}
	}

	function onDropEvent(e: DragEvent) {
		const dt = e.dataTransfer;

		if (dt === null) {
			return;
		}

		e.preventDefault();

		setActive(false);

		if (onDragOut) {
			onDragOut()
		}

		const files = Array.from(getFiles(dt));

		onDrop(files)

		// this.$emit('update:modelValue', files);
	}

	function onDragLeave(e: DragEvent) {

		if (active && dropRef.current) {
			const size = dropRef.current?.getBoundingClientRect();

			if (!(e.pageX >= size.left && e.pageX <= size.right
				&& e.pageY >= size.top && e.pageY <= size.bottom)) {
				setActive(false);
				if (onDragOut) {
					onDragOut()
				}
			}
		}
	}


	function onDragEnter(e: DragEvent<HTMLDivElement>) {
		if (!active && dropRef.current) {
			const size = dropRef.current?.getBoundingClientRect();

			if (e.pageX >= size.left && e.pageX <= size.right
				&& e.pageY >= size.top && e.pageY <= size.bottom) {
				setActive(true);
				if (onDragIn) {
					onDragIn()
				}
			}
		}
	}

	function onDragOver(e: DragEvent) {
		e.preventDefault()
	}

	return 	<div className={'drop-target' + (active ? ' active' : '')}
			style={{'border': active ? '1px solid var(--color-status-good)' : 'none'}}
			ref={dropRef}
			onDrop={onDropEvent}
			onDragEnter={onDragEnter}
			onDragLeave={onDragLeave}
			onDragOver={onDragOver}>
		{children}
	</div>
}
